#spring.application.name=SpringBootProjetest
#server.port=9090
server.port=${PORT:9090}

#spring.jackson.serialization.indent-output=true

server.tomcat.threads.max=200
server.tomcat.accept-count=590


#Cat timp asteptam dupa ce conexiunea s-a realizat (connected socket establesd)
#Daca nu trimite nimic timp de 2000ms (2s) atunci conexiune se inchide =>socked closed
#server.tomcat.connection-timeout=20000


# Dupa primul request trimis.. cat timp rezonabil mai astept pana cand consider
# ca pot elibera conexiunea...
server.tomcat.keep-alive-timeout=20000

# Numarul maxim de request-uri keep-alive pe aceeasi conexiune
#server.tomcat.max-keep-alive-requests=100

spring.datasource.url=jdbc:mysql://localhost:3306/qa_demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true